# Generated by Django 3.2 on 2025-02-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_subscribe_follower'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inshoppingcart',
            name='user-shopping_cart',
        ),
        migrations.AddConstraint(
            model_name='inshoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user-inshoppingcart'),
        ),
    ]
